# Generated by Django 4.0.1 on 2022-12-13 11:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MlWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('creation_ts', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('last_update', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('last_save', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('wf_json', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_workflow',
            },
        ),
    ]
