# Generated by Django 4.1 on 2022-11-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(null=True)),
                ("model_name", models.TextField(null=True)),
                ("username", models.TextField(null=True)),
                ("description", models.TextField(null=True)),
                ("version", models.FloatField(null=True)),
                ("eval_metrics", models.TextField(null=True)),
                ("columns", models.TextField(null=True)),
            ],
            options={
                "db_table": "services",
            },
        ),
    ]
