# Generated by Django 4.1 on 2022-11-03 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "private",
                    models.ManyToManyField(
                        related_name="private", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "purchased",
                    models.ManyToManyField(
                        related_name="purchased", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "items",
            },
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=1000)),
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="dataset_relation",
                        serialize=False,
                        to="items.item",
                    ),
                ),
            ],
            options={
                "db_table": "datasets",
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=200)),
                ("uploadDate", models.TimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "file",
            },
        ),
        migrations.CreateModel(
            name="VisualAnalytics",
            fields=[
                ("name", models.CharField(max_length=200)),
                ("tableau_workbook_id", models.CharField(max_length=200)),
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="va_relation",
                        serialize=False,
                        to="items.item",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="items.dataset"
                    ),
                ),
            ],
            options={
                "db_table": "visualanalytic",
            },
        ),
        migrations.AddField(
            model_name="dataset",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="items.file"
            ),
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("name", models.CharField(max_length=200)),
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="asset_relation",
                        serialize=False,
                        to="items.item",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="items.file"
                    ),
                ),
            ],
            options={
                "db_table": "assets",
            },
        ),
    ]
